import { defineObject, FieldType } from 'twenty-sdk/define';

import { INVOICE_IDENTIFIERS } from '../constants/invoicing-identifiers';

export default defineObject({
  universalIdentifier: INVOICE_IDENTIFIERS.object,
  nameSingular: 'accountingInvoice',
  namePlural: 'accountingInvoices',
  labelSingular: 'Factura',
  labelPlural: 'Facturas',
  description: 'Factura vinculada a un emisor y un cliente.',
  icon: 'IconFileInvoice',
  labelIdentifierFieldMetadataUniversalIdentifier: INVOICE_IDENTIFIERS.numberField,
  fields: [
    {
      universalIdentifier: INVOICE_IDENTIFIERS.dateField,
      type: FieldType.DATE,
      name: 'date',
      label: 'Fecha',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      universalIdentifier: INVOICE_IDENTIFIERS.typeField,
      type: FieldType.TEXT,
      name: 'invoiceType',
      label: 'Tipo',
      description: 'Tipo de comprobante, por ejemplo A, B o C.',
      icon: 'IconAbc',
      isNullable: true,
    },
    {
      universalIdentifier: INVOICE_IDENTIFIERS.numberField,
      type: FieldType.TEXT,
      name: 'number',
      label: 'Número',
      description: 'Número de comprobante, conservando ceros y punto de venta.',
      icon: 'IconHash',
      isNullable: false,
      defaultValue: "''",
    },
    {
      universalIdentifier: INVOICE_IDENTIFIERS.totalField,
      type: FieldType.CURRENCY,
      name: 'total',
      label: 'Total',
      icon: 'IconCurrencyDollar',
      isNullable: true,
      defaultValue: { amountMicros: null, currencyCode: "'ARS'" },
    },
    {
      universalIdentifier: INVOICE_IDENTIFIERS.paidField,
      type: FieldType.BOOLEAN,
      name: 'paid',
      label: 'Pagado',
      icon: 'IconToggleLeft',
      isNullable: false,
      defaultValue: false,
    },
    {
      universalIdentifier: INVOICE_IDENTIFIERS.balanceField,
      type: FieldType.CURRENCY,
      name: 'balance',
      label: 'Saldo',
      description: 'Saldo pendiente de cobro, actualizado manualmente.',
      icon: 'IconCurrencyDollar',
      isNullable: true,
      defaultValue: { amountMicros: null, currencyCode: "'ARS'" },
    },
    {
      universalIdentifier: INVOICE_IDENTIFIERS.statusField,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Estado',
      icon: 'IconProgress',
      isNullable: false,
      defaultValue: "'DRAFT'",
      options: [
        {
          id: INVOICE_IDENTIFIERS.issuedOption,
          value: 'ISSUED',
          label: 'Emitida',
          color: 'green',
          position: 0,
        },
        {
          id: INVOICE_IDENTIFIERS.draftOption,
          value: 'DRAFT',
          label: 'Borrador',
          color: 'gray',
          position: 1,
        },
        {
          id: INVOICE_IDENTIFIERS.pendingSendOption,
          value: 'PENDING_SEND',
          label: 'Pendiente de envío',
          color: 'orange',
          position: 2,
        },
        {
          id: INVOICE_IDENTIFIERS.rejectedOption,
          value: 'REJECTED',
          label: 'Rechazada',
          color: 'red',
          position: 3,
        },
        {
          id: INVOICE_IDENTIFIERS.cancelledOption,
          value: 'CANCELLED',
          label: 'Anulada',
          color: 'gray',
          position: 4,
        },
      ],
    },
    {
      universalIdentifier: INVOICE_IDENTIFIERS.authorizationCodeField,
      type: FieldType.TEXT,
      name: 'authorizationCode',
      label: 'CAE',
      icon: 'IconHash',
      isNullable: true,
    },
  ],
});
